### ISSUE TITLE
启动后无界面

### ISSUE THREAD

**Issue by orangle** [MoeFE/GoogleTranslate#119]
* MACOS 10.13.6
* 软件版本 google-translate-2.0.0-beta.2-mac

现象：下载之后解压并打开，提示来源问题（已经设置任何来源信任），这个时候dock上是有图标显示的，点击确定之后dock和最上面的图标栏都没有这个APP的信息。 通过 活动监视器可以看到进程。

我应该提供什么信息呢?

**Comment by mantou132** [comment]
应该是主进程中的 js 报错了。

**Comment by u3u** [comment]
将下面的内容复制到终端运行看看有没有错误信息：

```bash
/Applications/Google\ 翻译.app/Contents/MacOS/Google\ 翻译
```

**Comment by orangle** [comment]
终端下
```
▶ /Applications/Google\ 翻译.app/Contents/MacOS/Google\ 翻译

```

没有错误信息。


查看进程 

```
ps -ef|grep 'Google 翻译'
  501 59528 56496   0  4:49下午 ttys014    0:00.00 grep --color=auto Google 翻译
  501 59525 66399   0  4:49下午 ttys017    0:00.54 /Applications/Google 翻译.app/Contents/MacOS/Google 翻译
  501 59526 59525   0  4:49下午 ttys017    0:00.13 /Applications/Google 翻译.app/Contents/Frameworks/Google 翻译 Helper.app/Contents/MacOS/Google 翻译 Helper --type=gpu-process --no-sandbox --supports-dual-gpus=false --gpu-driver-bug-workarounds=0,1,5,12,27,30,43,47,56,62,70,73,74,75,76,83,84,86,94,95,96,100,103 --disable-gl-extensions=GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent --gpu-vendor-id=0x8086 --gpu-device-id=0x162b --gpu-driver-vendor --gpu-driver-version --gpu-driver-date --gpu-active-vendor-id=0x8086 --gpu-active-device-id=0x162b --service-request-channel-token=4DC359D26BCE587023319A3D298AB35E
```

奇了怪

**Comment by u3u** [comment]
强制退出进程再打开也是这样吗？

**Comment by orangle** [comment]
嗯 会不会跟其他啥程序冲突了，电脑装的东西乱七八糟的。

**Comment by u3u** [comment]
@orangle 现在还无法确定原因，如果可以的话，克隆源代码下来，尝试在开发环境下运行一下

具体操作步骤：

1. 下载最新版本的 [Node.js](https://nodejs.org/dist/v10.10.0/node-v10.10.0.pkg)

2. 使用 Brew 安装 Yarn

```bash
brew install yarn
```

3. 克隆源代码并进入项目根目录

```bash
git clone git@github.com:MoeFE/GoogleTranslate.git && cd GoogleTranslate
```

4. 使用 Yarn 安装依赖

```bash
yarn
```

5. 重新编译 robotjs

```bash
yarn rebuild
```

6. 启动应用程序

```bash
yarn serve
```

**Comment by orangle** [comment]
启动时候的控制台信息

```
yarn run v1.7.0
$ vue-cli-service serve:electron

Starting development server:

 INFO  Starting development server...
Starting type checking service...
Using 1 worker with 2048MB memory limit
 98% after emitting CopyPlugin

 DONE  Compiled successfully in 4599ms                                                                                                            下午12:35:14

Type checking in progress...

  App running at:
  - Local:   http://localhost:8080/
  - Network: http://192.168.1.30:8080/

  Note that the development build is not optimized.
  To create a production build, run yarn build.

Bundling main process:

[ './node_modules/keyv/src/index.js 18:14-40\nCritical dependency: the request of a dependency is an expression\n    at CommonJsRequireContextDependency.getWarnings (/Users/liuzhizhi/githouse/GoogleTranslate/node_modules/webpack/lib/dependencies/ContextDependency.js:40:18)\n    at Compilation.reportDependencyErrorsAndWarnings (/Users/liuzhizhi/githouse/GoogleTranslate/node_modules/webpack/lib/Compilation.js:1325:24)\n    at Compilation.finish (/Users/liuzhizhi/githouse/GoogleTranslate/node_modules/webpack/lib/Compilation.js:1136:9)\n    at hooks.make.callAsync.err (/Users/liuzhizhi/githouse/GoogleTranslate/node_modules/webpack/lib/Compiler.js:545:17)\n    at _err0 (eval at create (/Users/liuzhizhi/githouse/GoogleTranslate/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)\n    at _addModuleChain (/Users/liuzhizhi/githouse/GoogleTranslate/node_modules/webpack/lib/Compilation.js:1064:12)\n    at processModuleDependencies.err (/Users/liuzhizhi/githouse/GoogleTranslate/node_modules/webpack/lib/Compilation.js:980:9)\n    at process._tickCallback (internal/process/next_tick.js:61:11)\n @ ./node_modules/cacheable-request/src/index.js\n @ ./node_modules/got/index.js\n @ ./node_modules/download/index.js\n @ ./src/main/checkForUpdates.js\n @ ./src/main/index.js\n @ multi ./src/main/index.js' ]
Hash: e0297e40118561051b0c
Version: webpack 4.17.2
Time: 3367ms
Built at: 2018/09/17 下午12:35:18
        Asset      Size      Chunks             Chunk Names
background.js  1.37 MiB  background  [emitted]  background
Entrypoint background = background.js
[./node_modules/download/index.js] 2.9 KiB {background} [built]
[./node_modules/vue-cli-plugin-electron-builder/lib/createProtocol.js] 1.22 KiB {background} [built]
[./node_modules/vue-cli-plugin-electron-builder/lib/index.js] 132 bytes {background} [built]
[./node_modules/vue-cli-plugin-electron-builder/lib/installVueDevtools/index.js] 1.6 KiB {background} [built]
[./package.json] 2.42 KiB {background} [built]
[./src/main/checkForUpdates.js] 625 bytes {background} [built]
[0] multi ./src/main/index.js 28 bytes {background} [built]
[./src/main/index.js] 4.16 KiB {background} [built]
[./src/main/lib/menubar/index.js] 4.98 KiB {background} [built]
[electron] external "electron" 42 bytes {background} [built]
[events] external "events" 42 bytes {background} [built]
[fs] external "fs" 42 bytes {background} [built]
[path] external "path" 42 bytes {background} [built]
[robotjs] external "require(\"robotjs\")" 42 bytes {background} [built]
[url] external "url" 42 bytes {background} [built]
    + 251 hidden modules

WARNING in ./node_modules/keyv/src/index.js 18:14-40
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/cacheable-request/src/index.js
 @ ./node_modules/got/index.js
 @ ./node_modules/download/index.js
 @ ./src/main/checkForUpdates.js
 @ ./src/main/index.js
 @ multi ./src/main/index.js

Launching Electron...
2018-09-17 12:35:19.046 Electron[26895:13193609] *** WARNING: Textured window <AtomNSWindow: 0x7fd87c4980a0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
[26895:0917/123520.335950:ERROR:CONSOLE(7574)] "Extension server error: Object not found: <top>", source: chrome-devtools://devtools/bundled/inspector.js (7574)
No type errors found
Version: typescript 3.0.3
Time: 12507ms

```

**Comment by u3u** [comment]
看起来并没有什么问题呀，运行之后问题依然出现吗？

**Comment by orangle** [comment]
乌龙了，是没有问题。原来是图标太多，顶部的菜单栏没有显示出来，我把很多图标关了就出现了。 我在找release版本试一试

**Comment by orangle** [comment]
release版本也是好用的。 囧，对不起大家了，搞了个乌龙。还是要感谢你们耐心指导

**Comment by u3u** [comment]
好的 图标太多的话我推荐你用 [Bartender](https://www.macbartender.com) 来折叠一些不常用的图标
